name: Puppeteer Scraper

on:
  workflow_dispatch:  # Allows manual runs from the GitHub Actions page

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use Node.js 16.x

    - name: Install dependencies
      run: |
        npm install  # Install Puppeteer and dependencies

    - name: Run Puppeteer scraper
      run: |
        node main.js  # Update to correct script name, assuming main.js is your script

    - name: Upload Excel output
      uses: actions/upload-artifact@v3
      with:
        name: scraper-output
        path: '*.xlsx'  # Upload the generated Excel file
