name: Puppeteer Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer scraper
      run: |
        # Update Puppeteer to use --no-sandbox and --disable-setuid-sandbox for headless environments
        node main.js
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - name: Upload Excel output
      uses: actions/upload-artifact@v3
      with:
        name: scraper-output
        path: 'output/*.xlsx'
